site_name: Kifurushi
site_description: kifurushi package documentation
site_author: Kevin Tewouda
site_url: https://kifurushi.readthedocs.io

repo_name: lewoudar/kifurushi
repo_url: https://github.com/lewoudar/kifurushi
edit_uri: tree/main/docs

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - API: api.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - mkautodoc
  - codehilite:
      css_class: highlight

extra_css:
  - css/custom.css
